# Site settings
author: Lester Young
title: A Coder's Journey
header-img: img/home-bg.png
email: lyoung070789@gmail.com
copyright_name: Lester Young
description: > # this means to ignore newlines until "baseurl:"
  From the beginning to beyond
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Lyoung0789

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

image:
  path: /_includes/typewrite.jpg
  height: 100
  width: 100
